name: Build Bicep and create Release draft

on:
  push:
    branches: [main]
    paths:
      - 'workbooks/**'
  pull_request:
    branches: [main]
    paths:
      - 'workbooks/**'

# on:
#   push:
#     # branches to consider in the event; optional, defaults to all
#     branches:
#       - main
#     # pull_request event is required only for autolabeler
#     pull_request:
#       # Only following types are handled by the action, but one can default to all as well
#       types: [opened, reopened, synchronize]
#     # pull_request_target event is required for autolabeler to support PRs from forks
#     pull_request_target:
#       types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main
      - name: Remove old ARM template
        run: rm -f workbooks/azuredeploy.json
      # Runs the bicep CLI action - individual files
      - name: Run Bicep build
        uses: aliencube/bicep-build-actions@v0.3
        with:
          files: workbooks/azuredeploy.bicep
      - name: Upload asset
        uses: actions/upload-artifact@v3
        with:
          name: azuredeploy.json
          path: workbooks/azuredeploy.json

  update_release_draft:
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR
    runs-on: ubuntu-latest
    if: github.event_name	== 'push'
    needs: build-and-attach
    steps:
      # (Optional) GitHub Enterprise requires GHE_HOST variable set
      #- name: Set GHE_HOST
      #  run: |
      #    echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV

      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        id: release_drafter
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        # with:
        #   config-name: my-config.yml
        #   disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Checkout code
      - uses: actions/checkout@main
      - name: Download asset
        uses: actions/download-artifact@v3
        with:
          name: azuredeploy.json
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.release_drafter.outputs.upload_url }}
          asset_path: |
            azuredeploy.json
            workbooks/Reliability Workbook.json
            workbooks/azuredeploy.bicep
          overwrite: true
      - name: Move asset
        run: |
          mv -f azuredeploy.json workbooks/azuredeploy.json
      - uses: EndBug/add-and-commit@v9.0.1
        with:
          author_name: github-actions
          author_email: '41898282+github-actions[bot]@users.noreply.github.com'
          message: Update Bicep-ARM template
          add: workbooks/azuredeploy.json
