name: Build Bicep and create Release draft

on:
  push:
    branches: [main]
    paths:
      - 'build/**'
  pull_request:
    branches: [main]
    paths:
      - 'build/**'

# on:
#   push:
#     # branches to consider in the event; optional, defaults to all
#     branches:
#       - main
#     # pull_request event is required only for autolabeler
#     pull_request:
#       # Only following types are handled by the action, but one can default to all as well
#       types: [opened, reopened, synchronize]
#     # pull_request_target event is required for autolabeler to support PRs from forks
#     pull_request_target:
#       types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: build
    steps:
      - uses: actions/checkout@main
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color -out tfplan -target local_file.armtemplate -target local_file.workbook

      - name: Terraform Apply
        run: terraform apply -no-color tfplan

      - name: Upload asset - azuredeploy.json
        uses: actions/upload-artifact@v3
        with:
          name: asset
          path: |
            build/azuredeploy.json
            build/ReliabilityWorkbook.json
          if-no-files-found: error

  update_release_draft:
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR
    runs-on: ubuntu-latest
    if: github.event_name	== 'push'
    needs: build-and-attach
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v5
        id: release_drafter
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        # with:
        #   config-name: my-config.yml
        #   disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Checkout code
      - uses: actions/checkout@main
#        with:
#          token: ${{secrets.FOR_COMMIT_BOT}}
      - name: Download asset
        uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -lR
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.release_drafter.outputs.upload_url }}
          asset_path: |
            asset/azuredeploy.json
            asset/ReliabilityWorkbook.json
          overwrite: true
      - name: Move asset
        run: |
          mv -f asset/azuredeploy.json asset/ReliabilityWorkbook.json workbooks/
#      - uses: EndBug/add-and-commit@v9.0.1
#        with:
#          author_name: github-actions
#          author_email: '41898282+github-actions[bot]@users.noreply.github.com'
#          message: Update ARM template and Workbook
#          add: |
#            workbooks/azuredeploy.json
#            workbooks/ReliabilityWorkbook.json
